fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -205,244 +205,244 @@ jobs:
          WORKFLOW_ID: ${CIRCLE_WORKFLOW_ID:0:7}
 
 
-#   configure-infrastructure:
-#     docker:
-#       - image: python:3.7-alpine3.11
+  configure-infrastructure:
+    docker:
+      - image: python:3.7-alpine3.11
 
-#     steps:
-#      - checkout
-#      - add_ssh_keys:
-#         fingerprints: ["4c:ca:7f:26:fe:6e:ee:31:5d:b6:98:4d:af:d8:c7:f4"]
-#      - attach_workspace:
-#         at: ~/
-#      - run:
-#         name: Install dependencies
-#         command: |
-#          apk add --update ansible
+    steps:
+     - checkout
+     - add_ssh_keys:
+        fingerprints: ["4c:ca:7f:26:fe:6e:ee:31:5d:b6:98:4d:af:d8:c7:f4"]
+     - attach_workspace:
+        at: ~/
+     - run:
+        name: Install dependencies
+        command: |
+         apk add --update ansible
 
-#      - run:
-#         name: Configure Server
-#         command:
-#          cd .circleci/ansible
-#          cat inventory.txt
-#          ansible-playbook -i inventory.txt configure-server.yml
-#      - destroy-environment:
-#         WORKFLOW_ID: ${CIRCLE_WORKFLOW_ID:0:7}
+     - run:
+        name: Configure Server
+        command:
+         cd .circleci/ansible
+         cat inventory.txt
+         ansible-playbook -i inventory.txt configure-server.yml
+     - destroy-environment:
+        WORKFLOW_ID: ${CIRCLE_WORKFLOW_ID:0:7}
     
 
-#   run-migrations:
-#     docker:
-#       - image: cimg/node:13.8.0
-#     steps:
-#       - checkout
-#       - install_nodejs
-#       - run:
-#           name: Run migrations
-#           command: |
-#              cd backend
-#              echo $TYPEORM_USERNAME
-#              npm install
-#              npm run build
-#              npm run migrations > migrations_dump.txt 
-#       - run:
-#           name: Send migration status to kvdb.io
-#           command: |
-#             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-#             then
-#             curl https://kvdb.io/4j8TUDzuquJrNddAZ31MTD/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
-#             fi
-#       - destroy-environment:
-#          WORKFLOW_ID: ${CIRCLE_WORKFLOW_ID:0:7}
-#       - revert-migrations: 
-#          Workflow_ID: ${CIRCLE_WORKFLOW_ID:0:7}
+  run-migrations:
+    docker:
+      - image: cimg/node:13.8.0
+    steps:
+      - checkout
+      - install_nodejs
+      - run:
+          name: Run migrations
+          command: |
+             cd backend
+             echo $TYPEORM_USERNAME
+             npm install
+             npm run build
+             npm run migrations > migrations_dump.txt 
+      - run:
+          name: Send migration status to kvdb.io
+          command: |
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+            curl https://kvdb.io/4j8TUDzuquJrNddAZ31MTD/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
+            fi
+      - destroy-environment:
+         WORKFLOW_ID: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations: 
+         Workflow_ID: ${CIRCLE_WORKFLOW_ID:0:7}
 
 
 
-#   deploy-frontend:
-#     docker:
-#      - image: cimg/base:stable
-#     steps:
-#       - checkout
-#       - install_awscli
-#       - install_nodejs
-#       - restore_cache:
-#          keys: [frontend-deps]
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             cd frontend
-#             npm install 
-#       - run:
-#           name: Get backend url
-#           command: |
-#             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-#             --filters "Name=tag:name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-#             --query 'Reservations[*].Instances[*].PublicIpAddress' \
-#             --output text)
-#             export API_URL="http://${BACKEND_IP}:3030"
-#             echo "API_URL = ${API_URL}"
-#             echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
-#             cat frontend/.env
-#       - run:
-#           name: Deploy frontend objects
-#           command: |
-#             cd frontend
-#             npm install
-#             npm run build
-#             tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
-#             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-#       - destroy-environment:
-#          WORKFLOW_ID: ${CIRCLE_WORKFLOW_ID:0:7}
-#       - revert-migrations: 
-#          Workflow_ID: ${CIRCLE_WORKFLOW_ID:0:7}
+  deploy-frontend:
+    docker:
+     - image: cimg/base:stable
+    steps:
+      - checkout
+      - install_awscli
+      - install_nodejs
+      - restore_cache:
+         keys: [frontend-deps]
+      - run:
+          name: Install dependencies
+          command: |
+            cd frontend
+            npm install 
+      - run:
+          name: Get backend url
+          command: |
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+            --filters "Name=tag:name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL = ${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            cat frontend/.env
+      - run:
+          name: Deploy frontend objects
+          command: |
+            cd frontend
+            npm install
+            npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+      - destroy-environment:
+         WORKFLOW_ID: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations: 
+         Workflow_ID: ${CIRCLE_WORKFLOW_ID:0:7}
            
                     
-#   deploy-backend:
+  deploy-backend:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - install_awscli
+      - install_ansible
+      - install_nodejs
+      - add_ssh_keys:
+          fingerprints: [4c:ca:7f:26:fe:6e:ee:31:5d:b6:98:4d:af:d8:c7:f4]
+      - attach_workspace:
+          at: ~/
+      - restore_cache:
+         keys: [backend-deps]
+      - run:
+          name: Install dependencies
+          command: |
+            cd backend
+            npm install
+     
+      - run:
+          name: Package Backend
+          command: |
+           cd backend
+           npm run build
+           tar -czf artifact.tar.gz dist/* package*
+           cd ..
+           cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
+      - run: 
+          name: Deploy backend
+          command: |
+           export TYPEORM_MIGRATIONS_DIR=./migrations
+           export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
+           export TYPEORM_MIGRATIONS=./migrations/*.ts
+
+           cd .circleci/ansible
+           cat inventory.txt
+           ansible-playbook -i inventory.txt deploy-backend.yml
+
+      - destroy-environment:
+         WORKFLOW_ID: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations: 
+         Workflow_ID: ${CIRCLE_WORKFLOW_ID:0:7}
+
+  smoke-test:
+    docker:
+      - image: cimg/base:stable 
+    steps:
+      - checkout
+      - install_awscli
+      - install_nodejs
+      - run:
+          name: Backend smoke test.
+          command: |
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+             --filters "Name=tag:name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+             --query 'Reservations[*].Instances[*].PublicIpAddress' \
+             --output text)
+
+            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+            if curl -s $API_URL/api/status | grep "ok"
+            then
+              exit 0
+            else
+              exit 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+            then
+              exit 1
+            else
+              exit 2
+            fi
+      - destroy-environment:
+         WORKFLOW_ID: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations: 
+         Workflow_ID: ${CIRCLE_WORKFLOW_ID:0:7}
+
+
+#   cloudfront-update:
 #     docker:
-#       - image: cimg/base:stable
+#       # Docker image here that supports AWS CLI
 #     steps:
-#       - checkout
-#       - install_awscli
-#       - install_ansible
-#       - install_nodejs
-#       - add_ssh_keys:
-#           fingerprints: [4c:ca:7f:26:fe:6e:ee:31:5d:b6:98:4d:af:d8:c7:f4]
-#       - attach_workspace:
-#           at: ~/
-#       - restore_cache:
-#          keys: [backend-deps]
+#       # Checkout code from git
 #       - run:
 #           name: Install dependencies
 #           command: |
-#             cd backend
-#             npm install
-     
+#             # your code here
 #       - run:
-#           name: Package Backend
+#           name: Update cloudfront distribution
 #           command: |
-#            cd backend
-#            npm run build
-#            tar -czf artifact.tar.gz dist/* package*
-#            cd ..
-#            cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
-#       - run: 
-#           name: Deploy backend
-#           command: |
-#            export TYPEORM_MIGRATIONS_DIR=./migrations
-#            export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
-#            export TYPEORM_MIGRATIONS=./migrations/*.ts
+#             # your code here
+#       # Here's where you will add some code to rollback on failure  
 
-#            cd .circleci/ansible
-#            cat inventory.txt
-#            ansible-playbook -i inventory.txt deploy-backend.yml
-
-#       - destroy-environment:
-#          WORKFLOW_ID: ${CIRCLE_WORKFLOW_ID:0:7}
-#       - revert-migrations: 
-#          Workflow_ID: ${CIRCLE_WORKFLOW_ID:0:7}
-
-#   smoke-test:
+# cleanup:
 #     docker:
-#       - image: cimg/base:stable 
+#       # Docker image here
 #     steps:
-#       - checkout
-#       - install_awscli
-#       - install_nodejs
+#       # Checkout code from git
 #       - run:
-#           name: Backend smoke test.
+#           name: Get old stack workflow id
 #           command: |
-#             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-#              --filters "Name=tag:name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-#              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-#              --output text)
-
-#             export API_URL=http://${BACKEND_PUBLIC_IP}:3030
-#             if curl -s $API_URL/api/status | grep "ok"
-#             then
-#               exit 0
-#             else
-#               exit 1
-#             fi
+#             # your code here
+#             export OldWorkflowID="the id here"
+#             export STACKS=[] #put the list of stacks here
 #       - run:
-#           name: Frontend smoke test.
+#           name: Remove old stacks and files
 #           command: |
-#             FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
-#             if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+#             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
 #             then
-#               exit 1
-#             else
-#               exit 2
+#               # your code here
 #             fi
-#       - destroy-environment:
-#          WORKFLOW_ID: ${CIRCLE_WORKFLOW_ID:0:7}
-#       - revert-migrations: 
-#          Workflow_ID: ${CIRCLE_WORKFLOW_ID:0:7}
-
-
-# #   cloudfront-update:
-# #     docker:
-# #       # Docker image here that supports AWS CLI
-# #     steps:
-# #       # Checkout code from git
-# #       - run:
-# #           name: Install dependencies
-# #           command: |
-# #             # your code here
-# #       - run:
-# #           name: Update cloudfront distribution
-# #           command: |
-# #             # your code here
-# #       # Here's where you will add some code to rollback on failure  
-
-# # cleanup:
-# #     docker:
-# #       # Docker image here
-# #     steps:
-# #       # Checkout code from git
-# #       - run:
-# #           name: Get old stack workflow id
-# #           command: |
-# #             # your code here
-# #             export OldWorkflowID="the id here"
-# #             export STACKS=[] #put the list of stacks here
-# #       - run:
-# #           name: Remove old stacks and files
-# #           command: |
-# #             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-# #             then
-# #               # your code here
-# #             fi
             
 
-# workflows:
-#   default:
-#     jobs:
-#       - build-frontend
-#       - build-backend
-#       - test-frontend:
-#           requires: [build-frontend]
-#       - test-backend:
-#           requires: [build-backend]
-#       - scan-backend:
-#           requires: [build-backend]
-#       - scan-frontend:
-#           requires: [build-frontend]
-#       - deploy-infrastructure:
-#           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-#           filters:
-#             branches:
-#               only: [master]
-#       - configure-infrastructure:
-#           requires: [deploy-infrastructure]
-#       - run-migrations:
-#           requires: [configure-infrastructure]
-#       - deploy-frontend:
-#           requires: [run-migrations]
-#       - deploy-backend:
-#           requires: [run-migrations]
-#       - smoke-test:
-#           requires: [deploy-backend, deploy-frontend]
-#       # - cloudfront-update:
-#       #     requires: [smoke-test]
-#       # - cleanup:
-#       #     requires: [cloudfront-update]
+workflows:
+  default:
+    jobs:
+      - build-frontend
+      - build-backend
+      - test-frontend:
+          requires: [build-frontend]
+      - test-backend:
+          requires: [build-backend]
+      - scan-backend:
+          requires: [build-backend]
+      - scan-frontend:
+          requires: [build-frontend]
+      - deploy-infrastructure:
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          filters:
+            branches:
+              only: [master]
+      - configure-infrastructure:
+          requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
+      - deploy-frontend:
+          requires: [run-migrations]
+      - deploy-backend:
+          requires: [run-migrations]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
+      # - cloudfront-update:
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]
